apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 3
  template:
    metadata:
      name: mynginx
    spec:
      containers:
        - name: myfirst-container
          image: mynginx
          ports:
            - containerPort: 80
